export default [
    { 'id': 1, 'question': 'Supplier of Amifix Blue R Special', 'options': ['Amtex Dye Chem', 'COLORBAND', 'DyStar'] },
    { 'id': 2, 'question': 'Supplier of Amifix Turq. Blue G', 'options': ['Amtex Dye Chem', 'KISCO', 'CHT India Pvt Ltd'] },
    { 'id': 3, 'question': 'Supplier of Amron HF Amr. Red HF3GL', 'options': ['Amtex Dye Chem', 'KISCO', 'Jay Dyes & Chem'] },
    { 'id': 4, 'question': 'Supplier of Avitera SE Avitera Navy SE', 'options': ['Ciba', 'COLORBAND', 'KISCO'] },
    { 'id': 5, 'question': 'Supplier of Levafix Brill Blue E-FFN', 'options': ['DyStar', 'COLORBAND', 'CHT India Pvt Ltd'] },
    { 'id': 6, 'question': 'Supplier of Syn Ultra Navy DS', 'options': ['KISCO', 'DyStar', 'Amtex Dye Chem'] },
    { 'id': 7, 'question': 'Supplier of Everacid Everacid Black X-BW', 'options': ['COLORBAND', 'Ardip Agency', 'Local supplier'] },
    { 'id': 8, 'question': 'Supplier of Jakazol CE - DIFF 60 Jak. Navy CE', 'options': ['Jay Dyes & Chem', 'Atul', 'Local supplier'] },
    { 'id': 9, 'question': 'Supplier of Coralene Navy Blue HP-GS', 'options': ['Ardip Agency', 'COLORBAND', 'KISCO'] },
    { 'id': 10, 'question': 'Supplier of Remazol Turquoise Blue G', 'options': ['DyStar', 'Amtex Dye Chem', 'COLORBAND'] },
    { 'id': 11, 'question': 'Supplier of Procion HE Red HE7B', 'options': ['Atul', 'DyStar', 'Ciba'] },
    { 'id': 12, 'question': 'Supplier of Dianix Dianix Black XF2', 'options': ['DyStar', 'COLORBAND', 'Ciba'] },
    { 'id': 13, 'question': 'Supplier of Procion Navy Blue HER', 'options': ['Atul', 'DyStar', 'Ciba'] },
    { 'id': 14, 'question': 'Supplier of Synozol Navy EC', 'options': ['KISCO', 'COLORBAND', 'DyStar'] },
    { 'id': 15, 'question': 'Supplier of Terasil Blue 3RL-02', 'options': ['Ciba', 'DyStar', 'Amtex Dye Chem'] },
    { 'id': 16, 'question': 'Supplier of Coralene Brill Red HP-3B', 'options': ['Ardip Agency', 'Ciba', 'CHT India Pvt Ltd'] },
    { 'id': 17, 'question': 'Supplier of Terasil Turq W-XN', 'options': ['Ciba', 'COLORBAND', 'Ardip Agency'] },
    { 'id': 18, 'question': 'Supplier of Cbcrylic Red GRL 200%', 'options': ['COLORBAND', 'CHT India Pvt Ltd', 'KISCO'] },
    { 'id': 19, 'question': 'Supplier of Amron HF Amr. Navy HFBF', 'options': ['DyStar', 'Ciba', 'COLORBAND'] },
    { 'id': 20, 'question': 'Supplier of Bzaktive Black SNN 01', 'options': ['CHT India Pvt Ltd', 'KISCO', 'Ardip Agency'] },
    { 'id': 21, 'question': 'Supplier of Remazol Blue RGB', 'options': ['DyStar', 'Atul', 'KISCO'] },
    { 'id': 22, 'question': 'Supplier of Avitera Yellow SE', 'options': ['Ciba', 'COLORBAND', 'KISCO'] },
    { 'id': 23, 'question': 'Supplier of Everacid Everacid Red ARL', 'options': ['COLORBAND', 'Ardip Agency', 'CHT India Pvt Ltd'] },
    { 'id': 24, 'question': 'Supplier of Procian Blue HEXL', 'options': ['Atul', 'DyStar', 'COLORBAND'] },
    { 'id': 25, 'question': 'Supplier of Amifix Turq. Blue G', 'options': ['Amtex Dye Chem', 'KISCO', 'CHT India Pvt Ltd'] }
];
export const answers = [0, 2, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 1, 2, 1, 2, 0, 1, 2, 1, 2, 1];
